#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

//---COMPUTE BUFFERS
#define PARTICLE_BUFFER_BIND_ID 0
#define UBO_UNIFORM_BIND_ID 3
//---VERTEX BUFFER
#define VERTEX_BUFFER_BIND_ID 0
#define INSTANCE_BUFFER_BIND_ID 1
#define VERTEX2_BUFFER_BIND_ID 2
#define UBO_BIND_ID 3


#define NUM_CREATURES_INIT 49
#define NUM_CREATURES_MAX 256

#define NUM_PARTICLES_INIT 30*30
#define NUM_PARTICLES_MAX  11000
#define INSTANCE_COUNT NUM_PARTICLES_MAX

#define NUM_PARTICLES_ADD NUM_PARTICLES_INIT

#define SCREEN_WIDTH 1600
#define SCREEN_HEIGHT 900

#define SIM_WIDTH  1800
#define SIM_HEIGHT 1800

#define MAP_SIZE_X 60
#define MAP_SIZE_Y 60

#define PARTICLE_RADIUS 1.0f

#define MAPCELL_MAX_PARTILCLES   30
#define NEIGHTB_MAX_PARTICLES    30
#define CONSTRAINTS_MAX_PARTICLE 300
#define CONSTRAINTS_MAX_LIMIT  NUM_PARTICLES_MAX*NUM_PARTICLES_MAX//+NUM_CREATURES_MAX*NUM_PARTICLES_MAX
#define CONSTRAINTS_PARTICLES_MAX_LIMIT  NUM_PARTICLES_MAX*NUM_PARTICLES_MAX

#endif // CONSTANTS_HPP


// Offscreen frame buffer properties
#define FB_DIM_X SIM_WIDTH/2
#define FB_DIM_Y (SIM_HEIGHT/2)*(SCREEN_HEIGHT/SCREEN_WIDTH)
#define FB_COLOR_FORMAT VK_FORMAT_R8G8B8A8_UNORM
